### ISSUE TITLE
Criar lógica responsável por Recompensa / Confiabilidade

### ISSUE THREAD

**Issue by thiagojacinto** [alvesmog/sprintCodeEcommerce#9]
Sugestão: Utilizar o pacote br.com...ecommerce.**POSVENDA**

+ instruções nas fotos

**Comment by thiagojacinto** [comment]
Pode ser um atributo direto da entidade PESSOA?

**Comment by alvesmog** [comment]
Qual a descrição, o CA e o CT dessa US?

**Comment by thiagojacinto** [comment]
> Qual a descrição, o CA e o CT dessa US?

O quê? Não entendi nada, @alvesmog hehehehe...

**Comment by thiagojacinto** [comment]
Na Venda já gera uma pontuação, **falta** transferir isso para o objeto Pessoa correspondente (comprador e/ou vendedor)

**Comment by thiagojacinto** [comment]
Reabrir por ainda não estar resolvido: é preciso comunicar a pontuação para o objeto Pessoa correspondente a Venda.
